### ISSUE TITLE
No support for PKCS7

### ISSUE THREAD

**Issue by hughsie** [AGProjects/python-gnutls#6]
I need to use gnutls from python to create a PKCS7 detached signature. I'm happy to do the work and open a PR with all the missing code but wanted to check you'd be open to merging this kind of patch. If so, I'm happy to add the missing bits for you. If not I can do something private, so I'm okay if you want to keep python-gnutls web-centric. Thanks!

**Comment by danpascu** [comment]
While I am not in principle opposed to exposing more of the underlying libgnutls functionality at the higher python level, I do not have the time and resources to commit to maintaining the cryptography part of the library long term, especially since I don't use it and it would quickly degrade.

I find the task of maintaining any cryptography library to be huge, given the fast rate of change in the field, so it would require someone deeply involved in the field to write a good, secure interface to cryptography functionality and also maintain it in the long run. Look for example at python-cryptography to get an idea of how complex things can be especially in providing an API with good, up to date and secure algorithms with good defaults.

I also do not like the idea to add just a tiny fraction of the gnutls crypto functionality. I'm of the mind that pyhton-gnutls should provide the full spectrum of the underlying crypto functionality or none at all.

When I first wrote python-gnutls was out of a need to make encrypted connections between a client and a server, where both the client and the server could verify each other through an X509 cert and in addition could inspect and verify individual fields inside the certificate to provide fine grained access to resources based on the certificate a client presented. None of this was available in the python openssl wrappers at the time (I'm not sure they are possible in them even nowadays). So python-gnutls came out of this need and it was focused to implement TLS connections with detailed X509 certificate validation and inspection.

That being said, if you are willing to write and maintain long term the cryptography part of python-gnutls, give it a go, but I'm wondering if it wouldn't be a better decision to try to extend something like python-cryptography which is already focused on cryptography functionality and it has a lot of knowledgeable and involved people behind it.

**Comment by hughsie** [comment]
> I find the task of maintaining any cryptography library to be huge

For sure! So far I've limited my changes to just doing the thinnest possible interface to libgnutls -- I'd really like to only audit C->libgnutls and python->libgnutls rather than C->libgnutls and python->libopenssl if at all possible. I did have a quick look at python-cryptography but I think it makes the PKCS7 much harder than it already is. I'll attach a PR and you can see what I mean.

Thanks for replying, it's appreciated.
